trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
 - group: vg-devops-bicep

stages:
- stage: Validate
  displayName: 'Validate Bicep'
  jobs:
  - job: Validate
    steps:
    - task: AzureCLI@2
      displayName: 'Run Bicep Build and What-If'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az bicep build --file infra/main.bicep

          az deployment group what-if \
            --resource-group $(devResourceGroup) \
            --template-file infra/main.bicep \
            --parameters @infra/parameters/dev.parameters.json \
            --parameters location=$(location)

- stage: Deploy_Dev
  displayName: 'Deploy to Dev'
  dependsOn: Validate
  condition: succeeded()
  jobs:
  - job: DeployDev
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Bicep to Dev'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment group create \
            --resource-group $(devResourceGroup) \
            --template-file infra/main.bicep \
            --parameters @infra/parameters/dev.parameters.json \
            --parameters location=$(location)
- stage: Deploy_Prod
dependsOn: Deploy_Dev
  jobs:
  - deployment: DeployProd
    environment: 'prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                ls -R
                az deployment group create \
                  --resource-group $(prodResourceGroup) \
                  --template-file infra/main.bicep \
                  --parameters @infra/parameters/prod.parameters.json \
                  --parameters location=$(location)